cmake_minimum_required(VERSION 3.20)
project(LunaPathConsumer LANGUAGES C CXX)
find_package(LunaPath CONFIG REQUIRED)
add_executable(lunapath_consumer_c main.c)
target_link_libraries(lunapath_consumer_c PRIVATE LunaPath::lunapath)
add_executable(lunapath_consumer_cpp main.cpp)
target_link_libraries(lunapath_consumer_cpp PRIVATE LunaPath::lunapath)
